repos:
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort
  #       require_serial: true
  #       types_or: [cython, pyi, python]
  #       args: ["--filter-files"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
        require_serial: true
        args:
          - -l
          - "119"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 6de8252c035844f1e679f509b5f37340b44d5c39
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        types: [python]
        args: [--py37-plus]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
