stages:
  - name: lint
  - name: test
  - name: deploy-pip
    if: tag IS present
  - name: deploy-docs
    if: tag IS present
  - name: deploy-release
    if: tag IS present

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
dist: xenial
sudo: true
install:
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install unittest2 mock; fi
  - python setup.py install
script:
  - make run_integration_tests
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then make run_acceptance_tests; fi

jobs:
  include:
    - stage: lint
      name: "Flakes"
      python:
        - "3.7"
      install:
        - pip install flake8
      script:
        - make flakes

    - stage: test
      name: "Tests"
      language: python
      after_success:
        - make coveralls

    - stage: deploy-pip
      name: "Publish to PyPi"
      python: '3.7'
      script:
        - pip install -r requirements-dev.txt
      deploy:
        provider: pypi
        user: AuHau-deploy
        distributions: sdist bdist_wheel
        skip_existing: true
        on:
          tags: true
          repo: magmax/python-inquirer
        password:
          secure: "U3TCm2jfVDh1jlsLUMNT+3gORy7QselNgXmLaAAVeFsmOjyxDNfQ0jfo7vVuv5/lMvDEJCe/ODDnAudM0YGKXB40viz1fMUddjK5y4PrSIbNG+EZMyLYh6AJt4J6wQuINeyUBiqDM+uV9iRscsEAv/m3Hx05UACPO3RQHRSHwkE="

    - stage: deploy-docs
      name: "Publish documentation"
      language: python
      python: '3.7'
      dist: xenial
      sudo: true
      install:
        - pip install -r requirements-doc.txt
        - pip install -e .
      script:
        - cd ./docs
        - make html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GH_TOKEN}
        keep_history: true
        committer_from_gh: true
        local_dir: ./docs/build/html/
        on:
          tags: true
          repo: magmax/python-inquirer

    - stage: deploy-release
      name: "Create release"
      python: '3.7'
      script: echo 'Lets do it!'
      deploy:
        provider: releases
        api_key: ${GH_TOKEN}
        on:
          tags: true
          repo: magmax/python-inquirer

notifications:
  email:
    on_success: change
    on_failure: change
